%%
%%

if: ifelse_bool block else block {

    // making Code save code to brevious branch
    lines.unnest();

    // obsługa else
    int goto_line = lines.code_size_cur() + help;
    int jump_line = lines.code_size_cur();

    gotoline(str("@%d", goto_line));

    lines.copy_buffer();
    lines.unnest();

    help-=2;
    addJumpForRel($1, jump_line);

    lines.copy_buffer();
}

else: ELSE{
    lines.nest();
}

ifelse_bool: IFELSE bool_exp{
    help+=2;
    $$ = $2;
    lines.nest();
}
